# .github/workflows/github-pages-deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Explicit jogosultságok
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'  # <-- JAVÍTVA: 3.16.0-ról 3.27.0-ra
          channel: 'stable'
      
      - name: Check Flutter version
        run: flutter --version
      
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build web
        run: |
            flutter build web --web-renderer html --base-href="/"
            cp ./build/web/index.html ./build/web/404.html
            echo "lpwave.hu" > ./build/web/CNAME
            touch ./build/web/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web